/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Commodity: typeof import('./../components/common/Commodity.vue')['default']
    CommodityList: typeof import('./../components/common/CommodityList.vue')['default']
    LayoutTabBar: typeof import('./../components/layout/LayoutTabBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
